---
openapi: 3.0.1
info:
  title: Clients API V1
  version: v1
paths:
  "/api/v1/accounts/{account_id}/contacts_collaborators":
    get:
      summary: Get all collaborators contact from an acccount
      tags:
      - Accounts
      security:
      - Bearer: []
      parameters:
      - name: account_id
        in: path
        description: id of the account
        required: true
        schema:
          type: integer
      responses:
        '404':
          description: contacts collaborators not found
        '200':
          description: contacts collaborators found
  "/api/v1/accounts/{account_id}/contacts":
    get:
      summary: Get all contact from an acccount
      tags:
      - Accounts
      security:
      - Bearer: []
      parameters:
      - name: account_id
        in: path
        description: id of the account
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: contacts found
        '404':
          description: contacts not found
  "/api/v1/accounts/{account_id}/contacts/{id}":
    get:
      summary: Get information of a contact from an acccount
      tags:
      - Accounts
      security:
      - Bearer: []
      parameters:
      - name: account_id
        in: path
        description: id of the account
        required: true
        schema:
          type: integer
      - name: id
        in: path
        description: id of the contact related to the account
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: contacts found
        '404':
          description: contacts not found
  "/api/v1/accounts/{account_id}/invitations":
    post:
      summary: Invite account contacts throght email
      tags:
      - Accounts
      security:
      - Bearer: []
      parameters:
      - name: account_id
        in: path
        description: id of the account
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: contacts invited
      requestBody:
        content:
          application/json:
            schema:
              type: array
  "/api/v1/accounts":
    get:
      summary: list accounts
      tags:
      - Accounts
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: headers
        description: autorizartion token with the user info
        schema:
          type: string
      responses:
        '200':
          description: Account information
        '401':
          description: Unauthorized
  "/api/v1/managers/{manager_id}/accounts/{account_id}/account_follow_ups":
    get:
      summary: Get all accounts follow ups for a manager and an  account
      tags:
      - Managers
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: headers
        description: autorizartion token with the user info
        schema:
          type: string
      - name: manager_id
        in: path
        description: id of the manager
        required: true
        schema:
          type: integer
      - name: account_id
        in: path
        description: id of the account
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: accounts follow ups found
    post:
      summary: Create a follow up for an account as a manager
      tags:
      - Managers
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: headers
        description: autorizartion token with the user info
        schema:
          type: string
      - name: manager_id
        in: path
        description: id of the manager
        required: true
        schema:
          type: integer
      - name: account_id
        in: path
        description: id of the account
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: create accounts follow ups found
  "/api/v1/managers/{manager_id}/accounts":
    get:
      summary: Get all accounts of a mannager and with priorities
      tags:
      - Managers
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: headers
        description: autorizartion token with the user info
        schema:
          type: string
      - name: manager_id
        in: path
        description: id of the manager
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: when I am an admin
  "/api/v1/managers/{id}":
    get:
      summary: show information of a manager
      tags:
      - Managers
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: headers
        description: autorizartion token with the user info
        schema:
          type: string
      - name: id
        in: path
        description: id of the manager collaborator
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: managers show
        '404':
          description: managers not found error
  "/api/v1/metric_history/{id}":
    get:
      summary: metric_history
      tags:
      - MetricHistory
      security:
      - Bearer: []
      parameters:
      - name: id
        in: path
        description: filter by category
        required: true
        schema:
          type: string
      - name: Authorization
        in: headers
        description: autorizartion token with the user info
        schema:
          type: string
      responses:
        '200':
          description: find metric historial
        '404':
          description: find metric historial
    put:
      summary: update metric
      tags:
      - metric
      security:
      - Bearer: []
      parameters:
      - name: id
        in: path
        required: true
      - name: Authorization
        in: headers
        description: autorizartion token with the user info
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/api/v1/teams/{team_id}/metrics":
    get:
      summary: Get metrics of team
      tags:
      - Metrics
      security:
      - Bearer: []
      parameters:
      - name: group_by
        in: query
        description: "[quarters, monthly]"
        schema:
          type: string
      - name: team_id
        in: path
        description: team id
        required: true
        schema:
          type: integer
      - name: indicator_type
        in: query
        description: "['balance', 'velocity', 'morale', 'performance']"
        schema:
          type: string
      responses:
        '200':
          description: metrics found
        '404':
          description: Not metrics found
  "/api/v1/posts/{id}":
    get:
      summary: Get a post of a collaborator
      tags:
      - Posts
      security:
      - Bearer: []
      parameters:
      - name: id
        in: path
        description: post id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: posts found
  "/api/v1/public/collaborators/{id}":
    get:
      summary: Get a collaborator
      tags:
      - Collaborators
      security:
      - Bearer: []
      parameters:
      - name: id
        in: path
        description: id of the collaborator
        required: true
        schema:
          type: integer
      - name: Authorization
        in: headers
        description: authorization token with the user info
        schema:
          type: string
      responses:
        '200':
          description: collaborator found
        '404':
          description: collaborator not found
  "/api/v1/public/collaborators":
    get:
      summary: Get talent pool directory
      tags:
      - Collaborators
      security:
      - Bearer: []
      parameters:
      - name: category
        in: query
        description: filter by category
        required: false
        allowReserved: true
        schema:
          type: string
      - name: Authorization
        in: headers
        description: authorization token with the user info
        schema:
          type: string
      responses:
        '200':
          description: talent pool directory filtered found
        '404':
          description: talent pool directory not found
  "/api/v1/team_morale/surveys/not_found":
    get:
      summary: Survey does not exist
      responses:
        '404':
          description: not found
  "/api/v1/team_morale/surveys/2":
    get:
      summary: Survey does not exist
      responses:
        '404':
          description: not found
  "/api/v1/team_morale/surveys/1":
    get:
      summary: get survey status
      responses:
        '200':
          description: successful
  "/api/v1/team_morale/survey_results":
    get:
      summary: list survey results with missing parameter
      tags:
      - Surveys
      parameters:
      - name: period
        in: query
        schema:
          type: string
      - name: year
        in: query
        schema:
          type: string
      - name: processing_type
        in: query
        schema:
          type: string
      responses:
        '200':
          description: successful
        '400':
          description: invalid request
  "/api/v1/team_morale/surveys":
    post:
      summary: Creates a Survey
      tags:
      - Surveys
      parameters: []
      responses:
        '200':
          description: survey created
        '400':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                team_id:
                  type: integer
                deadline:
                  type: date
                period:
                  type: string
                period_value:
                  type: integer
                year:
                  type: integer
                survey_url:
                  type: string
                description:
                  type: string
              required:
              - team_id
              - deadline
              - period
              - period_value
              - year
              - survey_url
              - description
    get:
      summary: surveys list
      responses:
        '200':
          description: successful
  "/api/v1/team_morale/surveys/{id}":
    delete:
      summary: close survey
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/api/v1/team_balance/balances":
    get:
      summary: list balances
      tags:
      - Balances
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: headers
        description: autorizartion token with the user info
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/api/v1/teams/{team_id}/collaborators":
    get:
      summary: list collaborators by team
      tags:
      - Teams
      security:
      - Bearer: []
      parameters:
      - name: Authorization
        in: headers
        description: autorizartion token with the user info
        schema:
          type: string
      - name: team_id
        in: path
        description: team id
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: teams collaborators index
  "/api/v1/teams/{team_id}/investments":
    get:
      summary: Investment data not found
      security:
      - Bearer: []
      parameters:
      - name: team_id
        in: path
        required: true
      - name: group_by
        in: query
      responses:
        '200':
          description: successful
        '404':
          description: not found
  "/build-info":
    get:
      summary: gets the build info
      tags:
      - Info
      responses:
        '200':
          description: info received
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/info"
servers:
- url: https://qa-clients-api.nordhen.com
- url: http://localhost:3000
components:
  securitySchemes:
    Bearer:
      description: JWT key necessary to use API calls
      type: apiKey
      name: Authorization
      in: header
  schemas:
    info:
      type: object
      properties:
        build_id:
          type: string
        build_date:
          type: string
        build_branch:
          type: string
      required:
      - build_id
      - build_date
      - build_branch
    manager_accounts:
      type: object
      properties:
        manager_accounts:
          type: object
          properties:
            id:
              type: integer
            name:
              type: string
            location:
              type: string
            last_follow_up_text:
              type: string
            priority:
              type: string
            role_debt:
              type: integer
            alert:
              type: boolean
            team_balance:
              type: object
              properties:
                amount:
                  type: object
                  properties:
                    value:
                      type: integer
                    alert:
                      type: boolean
                alert:
                  type: boolean
            client_management:
              type: object
              properties:
                amount:
                  type: object
                  properties:
                    value:
                      type: integer
                    alert:
                      type: boolean
                alert:
                  type: boolean
            performance:
              type: object
              properties:
                amount:
                  type: object
                  properties:
                    value:
                      type: integer
                    alert:
                      type: boolean
                alert:
                  type: boolean
            gross_margin:
              type: object
              properties:
                amount:
                  type: object
                  properties:
                    value:
                      type: integer
                    alert:
                      type: boolean
                alert:
                  type: boolean
            morale:
              type: object
              properties:
                amount:
                  type: object
                  properties:
                    value:
                      type: integer
                    alert:
                      type: boolean
                alert:
                  type: boolean
          required:
          - id
          - name
          - location
          - last_follow_up_text
          - priority
          - role_debt
          - alert
          - team_balance
          - client_management
          - performance
          - gross_margin
          - morale
    metric:
      type: object
      properties:
        metric:
          type: object
          properties:
            metrics:
              type: string
            indicator_type:
              type: string
            date:
              type: string
            related_type:
              type: string
            related_id:
              type: integer
          required:
          - metrics
          - indicator_type
          - date
          - related_type
          - related_id
    team:
      type: object
      properties:
        metric:
          type: object
          properties:
            added_date:
              type: string
            team_type_id:
              type: integer
            project_id:
              type: integer
          required:
          - added_date
          - team_type_id
          - project_id
