shared:
  workers:
    - Accounts::ClientUserCreatedSubscriber
    - Accounts::ClientUserFailedSubscriber
  amqp_url: <%= ENV.fetch("CLOUDAMQP_URL", "amqp://guest:guest@rabbitmq:5672") %>
  exchange: "norden"
  vhost: <%= ENV.fetch("CLOUDAMQP_VHOST", "/") %>
  max_workers: 2
  max_threads: 3
development:
  connection_name: core_development
qa:
  connection_name: core_qa
staging:
  connection_name: core_staging
production:
  connection_name: core_production
